# Generated by Django 4.0.5 on 2022-07-11 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_dailytask_daily'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daily',
            options={'verbose_name': 'Daily', 'verbose_name_plural': 'Daily'},
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
