# Generated by Django 4.0.5 on 2022-07-11 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_daily_options_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='daily',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily', to='projects.daily'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'ToDo'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DUE', 'Due')], default='TODO', max_length=16),
        ),
    ]
