# Generated by Django 4.0.5 on 2022-07-11 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_task_daily_alter_task_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='end_date',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='end_time',
            new_name='due_time',
        ),
    ]
