# Generated by Django 4.0.5 on 2022-07-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_task_daily_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'todo'), ('inProgress', 'inProgress'), ('complete', 'complete'), ('due', 'due')], default='TODO', max_length=16),
        ),
    ]
